# Generated by Django 3.0.6 on 2020-06-23 09:04

from django.db import migrations, models
from printer.models import *


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Printers_Stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('serial_number', models.CharField(max_length=200, unique=True, verbose_name='Серийный номер')),
                ('name_printers', models.CharField(max_length=200, verbose_name='Имя принтера')),
                ('ip_address', models.CharField(max_length=200, verbose_name='IP адрес')),
                ('type_printers', models.CharField(max_length=200, verbose_name='Тип принтера')),
                ('page_count', models.CharField(max_length=200, verbose_name='Количество отпечатанных страниц')),
                ('capacity_toner_black', models.CharField(max_length=200, verbose_name='Емкость Черный')),
                ('toner_count_black', models.CharField(max_length=200, verbose_name='Черный')),
                ('capacity_toner_cyan', models.CharField(default='', max_length=200, verbose_name='Емкость Синий')),
                ('toner_count_cyan', models.CharField(default='', max_length=200, verbose_name='Синий')),
                ('capacity_toner_magenta', models.CharField(default='', max_length=200, verbose_name='Емкость Красный')),
                ('toner_count_magenta', models.CharField(default='', max_length=200, verbose_name='Красный')),
                ('capacity_toner_yellow', models.CharField(default='', max_length=200, verbose_name='Емкость Желтый')),
                ('toner_count_yellow', models.CharField(default='', max_length=200, verbose_name='Желтый')),
                ('cartridge_type', models.CharField(default='', max_length=200, verbose_name='Тип картриджа')),


            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
