# Generated by Django 3.0.6 on 2020-06-23 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printers_stat',
            name='type_printers',
        ),
    ]
