# Generated by Django 3.0.6 on 2020-06-23 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0002_remove_printers_stat_type_printers'),
    ]

    operations = [
        migrations.AddField(
            model_name='printers_stat',
            name='cartridge_type',
            field=models.CharField(default='', max_length=200, verbose_name='Тип картриджа'),
        ),
    ]
