# Generated by Django 3.0.6 on 2020-06-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0004_auto_20200623_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printers_stat',
            name='serial_number',
            field=models.CharField(max_length=200, unique=True, verbose_name='Серийный номер'),
        ),
    ]
