# Generated by Django 3.0.6 on 2020-06-23 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0005_auto_20200623_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printers_stat',
            name='capacity_toner_black',
            field=models.CharField(max_length=200, verbose_name='Емкость Черный'),
        ),
        migrations.AlterField(
            model_name='printers_stat',
            name='ip_address',
            field=models.CharField(max_length=200, verbose_name='IP адрес'),
        ),
        migrations.AlterField(
            model_name='printers_stat',
            name='name_printers',
            field=models.CharField(max_length=200, verbose_name='Имя принтера'),
        ),
        migrations.AlterField(
            model_name='printers_stat',
            name='page_count',
            field=models.CharField(max_length=200, verbose_name='Количество отпечатанных страниц'),
        ),
        migrations.AlterField(
            model_name='printers_stat',
            name='toner_count_black',
            field=models.CharField(max_length=200, verbose_name='Черный'),
        ),
        migrations.AlterField(
            model_name='printers_stat',
            name='type_printers',
            field=models.CharField(max_length=200, verbose_name='Тип принтера'),
        ),
    ]
