# Generated by Django 3.0.6 on 2020-06-25 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0006_auto_20200623_1652'),
    ]

    operations = [
    ]
