# Generated by Django 3.0.6 on 2020-06-26 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0007_auto_20200625_0931'),
    ]

    operations = [
        migrations.CreateModel(
            name='Printer_Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('name_printers', models.CharField(max_length=200, verbose_name='Имя принтера')),
                ('toner_black', models.CharField(max_length=200, verbose_name='Черный')),
                ('toner_cyan', models.CharField(max_length=200, verbose_name='Синий')),
                ('toner_magenta', models.CharField(max_length=200, verbose_name='Красный')),
                ('toner_yellow', models.CharField(max_length=200, verbose_name='Желтый')),
            ],
            options={
                'ordering': ['-datetime'],
            },
        ),
    ]
