# Generated by Django 3.0.6 on 2020-06-26 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0008_printer_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer_color',
            name='toner_black',
            field=models.IntegerField(max_length=200, verbose_name='Черный'),
        ),
        migrations.AlterField(
            model_name='printer_color',
            name='toner_cyan',
            field=models.IntegerField(max_length=200, verbose_name='Синий'),
        ),
        migrations.AlterField(
            model_name='printer_color',
            name='toner_magenta',
            field=models.IntegerField(max_length=200, verbose_name='Красный'),
        ),
        migrations.AlterField(
            model_name='printer_color',
            name='toner_yellow',
            field=models.IntegerField(max_length=200, verbose_name='Желтый'),
        ),
    ]
